### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ttoine**

### CODE REVIEW

**Review by olecorre — APPROVED** [review]

**Comment by Max84** [comment]
Hi @ttoine 
You've have deleted the [21] links to the contributors files.
Maybe it can be bad understand by them ?

**Comment by ttoine** [comment]
@Max84 actually, the contributors file is still in the repository.
the purpose of this edition is to make it clear about what will be merged, and what will not be merged. and why.
people who wants more information should go on the main repository or on the devdoc, ...

**Review by Max84 — APPROVED** [review]

**Comment by ttoine** [comment]
Hello, now that it has been approved by 2 maintainers, could one of you merge it? This way it will be visible when someone comes on the repo.

**Comment by ttoine** [comment]
BTW, the merging rights have been corrected, you should be able to merge.

**Comment by ttoine** [comment]
thanks :-)

**Comment by Max84** [comment]
With rights it's better ;) 
I think i couldn't merge myself because i validated commit.

**Pull request merged**
