### PR TITLE
Make sure the user is connected before submit reorder

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Replicate security fix from PS 1.7 introduced in this commit https://github.com/PrestaShop/PrestaShop/commit/3afc5a663c49eb9d727f3fc0004d78c4a8ff8e39
| Type?         | bug fix

### CODE REVIEW

**Comment by olecorre** [comment]
Good form me

**Review by olecorre — DISMISSED** [review]

**Review by Max84 — DISMISSED** [review]
It's ok, thanks for this PR.

**Comment by Max84** [comment]
Humm, Travis is worried with php 5.6. I tested onto php 7. You should have to fix it for php 5.6 too in order to allow pull request merging.

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
@Max84 yep that's strange tho. I fixed Travis on PR https://github.com/PrestaShop/PrestaShop-1.6/pull/4/ . It might be due to an update in a dependency. Someone see something to change for PHP 5.6 ?

**Comment by ghost** [comment]
I was able to find what was blocking with Travis checks.
The error comes from the following test : `ModulesInstallUninstallTest::testInstallationAndUnInstallation` with `ps_checkout`
```
PHP Fatal error:  Call to undefined method Symfony\Component\Yaml\Parser::parseFile() in /home/vagrant/code/prestashops/github-PrestaShop-1.6/modules/ps_checkout/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php on line 664
```
I didn't however find the exact reason of the error, but I suppose this might be due to phpunit version or something similar. For the time being I "Fixed" the issue by excluding ps_checkout module in the unit test.

**Comment by ghost** [comment]
@Max84 @okom3pom @olecorre , The checks passed following the last change. Please let me know if you validate the PR.

**Comment by olecorre** [comment]
Dood for me

**Review by olecorre — APPROVED** [review]

**Comment by Max84** [comment]
It's still OK for me, i reapprove it.

**Review by Max84 — APPROVED** [review]

**Comment by Max84** [comment]
Merged, thanks @infiniweb 👍

**Pull request merged**
